baseURL = "https://asrob.eu"
languageCode = "en-us"
title = "asrob.eu"

theme = "coder"

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Peter Borsa"
    info = "DevOps guy"
    description = "Peter Borsa's personal website"
    keywords = "blog,developer,devops,personal"

    # wether you want to hide copyright and credits in the footer
    hideCredits = false
    hideCopyright = true

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/asrob/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/peter_borsa/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/asrob/"
[[params.social]]
    name = "Facebook"
    weight = 4
    url = "https://www.facebook.com/asrob/"
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.speakerDeck]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
